Polling/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exam.urls')),
    path('account/', include('user_profile.urls')),
]

exam/urls.py
from django.urls import path
from .views import HomePage, QuestionDetail, QuestionList

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('<pk>/<question>', QuestionDetail.as_view(), name='detail'),
    path('questions', QuestionList.as_view(), name='questions')
]

user_profile/urls.py
from django.urls import path
from .views import Login, Register, AddQuestion

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('signup/', Register.as_view(), name='register'),
    path('', AddQuestion.as_view(), name='addquest'),
]

exam/models.py
from django.db import models


# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=50, unique=True)
    question = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"{self.id}/{self.title.replace(' ', '-')}"


class Answer(models.Model):
    answer = models.CharField(max_length=100)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer

user_profile/forms.py
from django import forms


class LoginForm(forms.Form):
    user_name = forms.CharField(
        widget=forms.TextInput())

    password = forms.CharField(
        widget=forms.PasswordInput())


class RegisterForm(forms.Form):
    user_name = forms.CharField(
        widget=forms.TextInput()
    )

    password = forms.CharField(
        widget=forms.PasswordInput()
    )

    re_password = forms.CharField(
        widget=forms.PasswordInput()
    )


class AddQuestionForm(forms.Form):
    title = forms.CharField(
        widget=forms.TextInput()
    )

    question = forms.CharField(
        widget=forms.Textarea()
    )

exam/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views import View
from .models import Question


# Create your views here.

class HomePage(ListView):
    queryset = Question.objects.all()[:5]
    template_name = 'home-page.html'
    context_object_name = 'questions'


class QuestionDetail(DetailView):
    template_name = 'question_detail.html'
    context_object_name = 'question'

    def get_queryset(self):
        question_id = self.kwargs.get('pk')
        question = Question.objects.filter(id=question_id)
        return question


class QuestionList(ListView):
    template_name = 'filter_quest.html'
    context_object_name = 'products'

    def get_queryset(self):
        query = self.request.GET.get('q')
        qs = Question.objects.all()
        if query:
            qs = Question.objects.filter(question__icontains=query)
        return qs

user_profile/views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, redirect
from django.views import View
from .forms import LoginForm, RegisterForm, AddQuestionForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User


# Create your views here.

class Login(View):
    def get(self, request):
        form = LoginForm()
        context = {
            'form': form
        }
        return render(request, 'login_page.html', context)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = self.request.POST.get("user_name")
            password = self.request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('home')
        else:
            return redirect('login')


class Register(View):
    def get(self, request):
        form = RegisterForm()
        context = {
            'form': form
        }
        return render(request, 'login_page.html', context)

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user_name = self.request.POST.get('user_name')
            password = self.request.POST.get('password')
            User.objects.create_user(username=user_name, password=password)
            return redirect('login')
        else:
            return HttpResponseNotAllowed('Not Allowed')


class AddQuestion(View):
    def get(self, request):
        form = AddQuestionForm()
        context = {
            'form': form
        }
        return render(request, 'add_question.html', context)

    def post(self):
        pass

templates/add_question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="">
    <input type="text" placeholder="تعداد جواب ها" name="answer">
</form>
<br>

<form action="" method="get">
    {% csrf_token %}
    {{ form }}
</form>

</body>
</html>

templates/filter_quest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="get">
    <input type="text" placeholder="جستـجو" name="q"/>
</form>

{% for question in object_list %}
    <a href="{{ question.get_absolute_url }}">{{ question.id }}-{{ question }}</a><br>
{% endfor %}

</body>
</html>

templates/home-page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div style="display: block">
    {% for question in questions %}
        <a href="{{ question.get_absolute_url }}">{{ question.id }}-{{ question }}</a><br>
    {% endfor %}
</div>

</body>
</html>

templates/login_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="send-data">
</form>
</body>
</html>

templates/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>{{ question }}</div>
<form action="">
    <p>{{ question.question }}</p>
    {% for answer in question.answer_set.all %}
        <input type="radio" id="{{ forloop.counter0 }}" name="question" value="{{ answer }}">
        <label for="{{ forloop.counter0 }}">{{ answer }}</label><br>
    {% endfor %}
</form>

</body>
</html>

templates/register_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="send-data">
</form>
</body>
</html>